name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            export APP_DIR="$HOME/apps/pethotel"
            export BRANCH="main"
            export FRONT_DIST_DIR="/var/www/pethotel"
            export JAR_TARGET_DIR="/opt/pethotel"
            export SERVICE_NAME="pethotel"
            bash "$APP_DIR/scripts/deploy.sh"
